name: Cron
on:
  workflow_dispatch:
  schedule:
      # Run every day at 2:30am PST (10:30am UTC)
    - cron: '30 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install deps
      run: bundle install
    - name: Run the default task
      run: bundle exec rake update-waivers
      env:
        SMARTWAIVER_API_KEY: ${{ secrets.SMARTWAIVER_API_KEY }}
        SCMA_FTP_USERNAME: ${{ secrets.SCMA_FTP_USERNAME }}
        SCMA_FTP_PASSWORD: ${{ secrets.SCMA_FTP_PASSWORD }}
