name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        SMARTWAIVER_API_KEY: ${{ secrets.SMARTWAIVER_API_KEY }}
        SCMA_FTP_USERNAME: ${{ secrets.SCMA_FTP_USERNAME }}
        SCMA_FTP_PASSWORD: ${{ secrets.SCMA_FTP_PASSWORD }}
